# -*- coding: utf-8 -*-
"""Ad_sales_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-OIQkMwCzcvm5j_P8sdpEcmaCo7Q9yzp
"""

# MODEL TO PREDICT IF CUSTOMER BUYS OR NOT
# BASIC ML MODEL USING LOGISTIC REGRESSION

# import needed libraries
import numpy as np
import pandas as pd

# read data
data = pd.read_csv("/content/DigitalAd_dataset.csv")

# exploring data
data.shape

data.head(5)
data.tail(5)

data.info()

data.describe()

# splitting X and Y separately
X = data.iloc[:,:-1]
X

Y = data.iloc[:,-1]
Y

# splitting dataset for 75% for training and 25% for testing
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

# feature scaling
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()

X_train = sd.fit_transform(X_train)
X_test = sd.transform(X_test)

X_train
X_test

# model training
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=0)

model = model.fit(X_train, y_train)

# model prediction
y_pred = model.predict(X_test)
y_pred

# checking model accuracy
from sklearn.metrics import accuracy_score
model_accuracy = (accuracy_score(y_test,y_pred))*100
model_accuracy

# predicting the Status value for a new data if given Age and Salary
Age = int(input("Enter Age of the new person : "))
Salary = int(input("Enter salary : "))
newVal = [[Age,Salary]]
newVal

# transform the new values
newVal = sd.transform(newVal)
newVal

# predicting Status for the new Value
newPred = model.predict(newVal)
newPred
if newPred == 1:
  print("Customer will buy")
else:
    print("Customer won't buy")

